/* tslint:disable */
/* eslint-disable */
/**
 * Music Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 * Contact: painassasin@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StaredTrack
 */
export interface StaredTrack {
    /**
     * 
     * @type {number}
     * @memberof StaredTrack
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof StaredTrack
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof StaredTrack
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof StaredTrack
     */
    'release_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaredTrack
     */
    'genre': string;
    /**
     * 
     * @type {number}
     * @memberof StaredTrack
     */
    'duration_in_seconds': number;
    /**
     * 
     * @type {string}
     * @memberof StaredTrack
     */
    'album': string;
    /**
     * 
     * @type {string}
     * @memberof StaredTrack
     */
    'logo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaredTrack
     */
    'track_file'?: string;
}

